name: social_forum
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  awesome_snackbar_content: ^0.1.3
  awesome_top_snackbar: ^0.0.3

  flame: ^1.18.0
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  google_mobile_ads: ^5.1.0
  http: ^1.2.2
  intl: ^0.19.0
  path: ^1.9.0
  provider: ^6.1.2
 
  sqflite: ^2.3.3+1
  unity_ads_plugin: ^0.3.17
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/icons/
   - assets/images/
  
  fonts:
    - family: Otoma
      fonts:
        - asset: assets/fonts/otoma.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/opensans.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito.ttf
